spring:
  profiles:
    active: dev

person:
  name: 0phone
  age: 18
  happy: false
  birth: 2020/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog:
    name: haha
    age: 1

person2:
  name: fivesixseven
  age: 20
  happy: true
  birth: 2020/01/02
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog:
    name: wangwang
    age: 2
